### ISSUE TITLE
升级的逻辑是什么

### ISSUE THREAD

**Issue by sheenhx** [azhon/flutter_app_update#10]
我在flutter版本看到代码里面只查询apk url，没有对比版本号是不是最新的，怎么样自动强制更新如果有新版本？

https://github.com/azhon/flutter_app_update/blob/5e190ec02662fa1de92b4965e4cd1e898608f363/lib/update_model.dart#L2

**Comment by azhon** [comment]
库只是一个下载器，没有版本判断逻辑。具体使用查看[示例代码](https://github.com/azhon/flutter_app_update/blob/main/example/lib/main.dart)

**Comment by sheenhx** [comment]
感谢！我们之前用一个sdk被谷歌下架了，用你这个试试

**Comment by azhon** [comment]
也应该会被下架，play禁止应用内更新
