### ISSUE TITLE
English documentation

### ISSUE THREAD

**Issue by EliasDalvite** [azhon/flutter_app_update#14]
Suggestion: Wouldn't it be better if the main details and examples were all in English, considering it's the default language of Pub.dev? This would greatly increase visibility for your project. 

It would also be helpful to have a more detailed explanation of how it operates, particularly regarding its compatibility with projects that won't utilize the Play Store for updates (which is my case). This information isn't stated anywhere, and I can't deduce it from studying the code.

Question: For example, can I link to a .apk file located inside Google? Would that work, or does the link need to point to the App Store/Play Store?

**Comment by azhon** [comment]
Already changed the default language to English.

Answer: must link need to point to the App Store/Play Store?

[Google Play Policy](https://support.google.com/googleplay/android-developer/answer/9888379?hl=en&ref_topic=9877467)

> Apps or third party code (for example, SDKs) that download executable code, such as dex files or native code, from a source other than Google Play.
