### ISSUE TITLE
Support for other languages

### ISSUE THREAD

**Issue by zuyie** [azhon/flutter_app_update#19]
Hi, would like to ask for a way to support for other languages.

now if the OS language is not English, it will display as Chinese.

Something like, "正在后台下载新版本...".

if not possible, is there a way to hide the above message or default to English?

**Comment by azhon** [comment]
You can modify these texts in res/values/strings.xml, just give the key the same name.
For other languages, just add string keys in values-xxx/strings.xml 
![image](https://github.com/user-attachments/assets/2d00d61e-efb5-47a1-919e-8053c0068b82)

**Comment by zuyie** [comment]
oo, where is the exact file location?
i don't see it in the whole flutter project

**Comment by zuyie** [comment]
https://pub.dev/documentation/flutter_app_update/latest/

is it written somewhere that i can refer to?

**Comment by azhon** [comment]
on YourProject/android/app/src/main/res/

**Comment by azhon** [comment]
> https://pub.dev/documentation/flutter_app_update/latest/
> 
> is it written somewhere that i can refer to?

Example：https://github.com/azhon/AppUpdate/tree/main/appupdate

**Comment by zuyie** [comment]
ok, thanks, will refer to the above example
